---
engines:
  eslint-9:
    enabled: true

# Exclude specific patterns in test files where they are false positives
# validation-utils.test.ts: RegExp constructor is used with pre-escaped strings
# to validate the escapeRegExp function behavior. These are intentional and safe.
exclude_patterns:
  - identifier: "Security/detect-non-literal-regexp"
    paths:
      - "src/utils/validation-utils.test.ts"
