---
# Coverage configuration for Codacy
coverage:
  # Coverage report paths
  paths:
    - coverage/lcov.info

  # Coverage thresholds
  thresholds:
    overall: 70
    file: 50

engines:
  eslint-9:
    enabled: true

# Exclude specific patterns in test files where they are false positives
# validation-utils.test.ts: RegExp constructor is used with pre-escaped strings
# to validate the escapeRegExp function behavior. These are intentional and safe.
# validation-sanitization.test.ts: HTML strings are intentionally used to test
# sanitizeInput and encodeHtmlEntities functions. These are not XSS vulnerabilities.
exclude_patterns:
  - identifier: "Security/detect-non-literal-regexp"
    paths:
      - "src/utils/validation-utils.test.ts"
  - identifier: "ESLint8_xss_no-mixed-html"
    paths:
      - "src/utils/validation-sanitization.test.ts"

# Exclude paths from code analysis
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - 'coverage/**'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - 'src/test/**'
  - 'scripts/**'
