---
engines:
  semgrep:
    enabled: true
  eslint-9:
    enabled: true
  eslint-8:
    enabled: true

exclude_paths:
  # Exclude build artifacts and dependencies
  - 'dist/**'
  - 'node_modules/**'
  - 'coverage/**'
  - '**/*.min.js'
