---
# Coverage configuration for Codacy
coverage:
  # Coverage report paths
  paths:
    - coverage/lcov.info

  # Coverage thresholds
  thresholds:
    overall: 70
    file: 70

engines:
  semgrep:
    enabled: true
  eslint-9:
    enabled: true
  eslint-8:
    enabled: true
  lizard:
    enabled: true
    exclude_paths:
      - '**/*.test.tsx'
      - '**/*.test.ts'
      - '**/*.spec.tsx'
      - '**/*.spec.ts'

# Exclude specific patterns in test files where they are false positives
# validation-utils.test.ts: RegExp constructor is used with pre-escaped strings
# to validate the escapeRegExp function behavior. These are intentional and safe.
# validation-sanitization.test.ts: HTML strings are intentionally used to test
# sanitizeInput and encodeHtmlEntities functions. These are not XSS vulnerabilities.
exclude_patterns:
  - identifier: "Security/detect-non-literal-regexp"
    paths:
      - "src/utils/validation-utils.test.ts"
  - identifier: "ESLint8_security_detect-non-literal-regexp"
    paths:
      - "src/utils/validation-utils.test.ts"
  - identifier: "ESLint8_xss_no-mixed-html"
    paths:
      - "src/utils/validation-sanitization.test.ts"

# Exclude paths from code analysis
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - 'coverage/**'
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - 'src/test/**'
  - 'scripts/**'
  - '**/*.min.js'

# Note: Codacy ESLint8 engine reports some false positive issues for non-literal RegExp
# patterns (ESLint8_security_detect-non-literal-regexp, ESLint8_security-node_non-literal-reg-expr).
# Most are now excluded via test file exclusions above.
# For any remaining false positives in component tests:
# 1. All RegExp inputs are sanitized via escapeRegExp() utility
# 2. Input sources are constants (FAQ_ITEMS, PRICING_PLANS, COMPETITORS), not user input
# 3. Semgrep scans these lines and approves them with inline nosemgrep suppressions
# 4. Every usage has clear safety documentation comments
#
# We attempted multiple suppression approaches:
# - Global exclude_patterns: Not recognized by Codacy
# - Engine-level exclusions: Not supported
# - Inline codacy-disable-next-line comments: Not working
# - Now using test file exclusions (exclude_paths) which works
#
# Any warnings in non-test files should be manually marked as "Won't Fix" or "False Positive" in Codacy UI.
