---
engines:
  eslint:
    enabled: true
    configuration_file: ".eslintrc.json"
  eslint-9:
    enabled: true

# Exclude specific patterns in test files where they are false positives
exclude_paths:
  - "dist/**"
  - "node_modules/**"
  - "coverage/**"
  - "reports/**"

# Ignore specific issues that are false positives
ignore_issues:
  - identifier: "Security/detect-non-literal-regexp"
    paths:
      - "src/utils/validation-utils.test.ts"
  - identifier: "ESLint8_xss_no-mixed-html"
    paths:
      - "src/utils/validation-sanitization.test.ts"
