---
engines:
  eslint-9:
    enabled: true

# Exclude specific patterns in test files where they are false positives
# validation-utils.test.ts intentionally uses RegExp constructor to validate escapeRegExp function
exclude_patterns:
  - identifier: "Security/detect-non-literal-regexp"
    paths:
      - "src/utils/validation-utils.test.ts"
