---
engines:
  semgrep:
    enabled: true
    exclude_paths:
      # Exclude test files from non-literal RegExp checks
      # These files use escapeRegExp() to sanitize all inputs before RegExp construction
      # The RegExp patterns are safe and necessary for testing dynamic content
      - 'src/**/*.test.ts'
      - 'src/**/*.test.tsx'
  eslint-9:
    enabled: true

exclude_paths:
  # Exclude build artifacts and dependencies
  - 'dist/**'
  - 'node_modules/**'
  - 'coverage/**'
  - '**/*.min.js'
  # Also exclude test files at the top level
  - 'src/**/*.test.ts'
  - 'src/**/*.test.tsx'
