---
engines:
  semgrep:
    enabled: true
  eslint-9:
    enabled: true
  eslint-8:
    enabled: true

exclude_paths:
  # Exclude build artifacts and dependencies
  - 'dist/**'
  - 'node_modules/**'
  - 'coverage/**'
  - '**/*.min.js'

exclude_patterns:
  # Disable ESLint security rules (we use Semgrep for these checks instead)
  # These patterns are false positives - all RegExp inputs are sanitized via escapeRegExp()
  - id: ESLint8_security_detect-non-literal-regexp
  - id: ESLint8_security-node_non-literal-reg-expr
  - id: ESLint9_security_detect-non-literal-regexp
  - id: ESLint9_security-node_non-literal-reg-expr
