sonar.projectKey=shazzar00ni_paperlyte-v2
sonar.organization=shazzar00ni
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=scripts/maintenance/**
