sonar.projectKey=shazzar00ni_paperlyte-v2
sonar.organization=shazzar00ni
sonar.sources=src
sonar.tests=src
sonar.exclusions=scripts/maintenance/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
