name: Dependency Check
on: [push]
permissions:
  contents: read
jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@1e54355a8b4c8abaa8cc7d0b70aa655a3bb15a6c # v5.5.0
        with:
          project: 'paperlyte-v2'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired
